name: Python package

on:
  push:
    branches: [ zero ]
  pull_request:
    branches: [ zero ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Lint with flake8
      run: poetry run flake8

    - name: Check formatting with black
      run: poetry run black --check .

    - name: Sort imports
      run: poetry run isort -c --df .

    - name: Check docstrings
      run: poetry run pydocstyle myia

    - name: Test with pytest
      run: poetry run pytest --cov=myia --cov-report term-missing

    - name: Verify coverage
      run: poetry run coverage report | tail -1 | egrep "TOTAL +[0-9]+ +0 +100%"
